### ISSUE TITLE
Chapter01 database password pairs do not work

### ISSUE THREAD

**Issue by Carl-Ty** [PacktPublishing/Hands-On-Docker-for-Microservices-with-Python#20]
Username password pairs provided in Chapter01 README.md do not work.
[Chapter01-loginFailure.pdf](https://github.com/PacktPublishing/Hands-On-Docker-for-Microservices-with-Python/files/5512490/Chapter01-loginFailure.pdf)

**Comment by echeadle** [comment]
Did you run this command? 
python manage.py loaddata thoughts/fixtures/thoughts.json thoughts/fixtures/users.json

It worked for me.

**Comment by Carl-Ty** [comment]
Running the command did fix the login issue.
