### ISSUE TITLE
Chapter01 - Set it up - load data - update the path for json file

### ISSUE THREAD

**Issue by m-cherni** [PacktPublishing/Hands-On-Docker-for-Microservices-with-Python#8]
In Set it up, update the path of the json files in the "Get the local database ready and load some initial data for testing", section:

python manage.py loaddata thoughts/fixtures/thoughts.json thoughts/fixtures/users.json

**Comment by jaimebuelta** [comment]
Thanks! Fixed here https://github.com/PacktPublishing/Hands-On-Docker-for-Microservices-with-Python/commit/165dbfb31399a3ed364268f41a1acc2c2190860f
